# Generated by Django 2.2.10 on 2020-06-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PS4_Games_Store', '0003_auto_20200602_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='Indica aqui la descripcion', max_length=2000),
        ),
    ]
