# Generated by Django 2.2.10 on 2020-06-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PS4_Games_Store', '0006_auto_20200602_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
