# Generated by Django 2.2.10 on 2020-06-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PS4_Games_Store', '0008_auto_20200602_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pedido', models.CharField(max_length=50)),
            ],
        ),
    ]
