# Generated by Django 2.2.10 on 2020-06-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PS4_Games_Store', '0009_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Pedido',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='nombre',
            new_name='usuario',
        ),
    ]
