# Generated by Django 2.2.10 on 2020-06-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PS4_Games_Store', '0012_auto_20200602_1731'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='jue',
            new_name='juego',
        ),
    ]
