# Generated by Django 2.2.10 on 2020-06-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PS4_Games_Store', '0013_auto_20200602_1731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
